version: '3.8'

services:
  srsepc:
    container_name: virtual-srsepc
    image: nouisser1/srsepc-4g:latest
    networks:
      corenet:
        ipv4_address: 10.80.95.10
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun

  srsenb:
    container_name: virtual-srsenb
    image: nouisser1/srsenb-4g:latest
    networks:
      corenet:
        ipv4_address: 10.80.95.11
      rfnet:
        ipv4_address: 10.80.97.11
    cap_add:
      - SYS_NICE
    depends_on:
      - srsepc

  srsue:
    container_name: virtual-srsue
    image: nouisser1/srsue-4g:latest
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    networks:
      rfnet:
        ipv4_address: 10.80.97.10
    depends_on:
      - srsenb

networks:
  corenet:
    ipam:
      driver: default
      config:
        - subnet: 10.80.95.0/24
  rfnet:
    ipam:
      driver: default
      config:
        - subnet: 10.80.97.0/24
