pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-token',
                    url: 'https://github.com/nwiuser/4g-5g-migration'
            }
        }
    }
}
