apiVersion: v1
kind: Service
metadata:
  name: srsepc
  namespace: srsran
spec:
  selector:
    app: srsepc
  ports:
    - name: mme
      protocol: TCP
      port: 36412
      targetPort: 36412
    - name: gtpu
      protocol: UDP
      port: 2152
      targetPort: 2152
  type: ClusterIP
