apiVersion: v1
kind: Service
metadata:
  name: srsepc
  labels:
    app: srsepc
spec:
  selector:
    app: srsepc
  ports:
    - name: s1-mme
      protocol: TCP
      port: 36412
      targetPort: 36412
    - name: gtpu
      protocol: UDP
      port: 2152
      targetPort: 2152
  clusterIP: None  # Headless service pour IP stable
