apiVersion: v1
kind: Service
metadata:
  name: srsue
  labels:
    app: srsue
spec:
  selector:
    app: srsue
  ports:
    - name: zmq-tx
      protocol: TCP
      port: 2001
      targetPort: 2001
  clusterIP: None
