apiVersion: apps/v1
kind: Deployment
metadata:
  name: srsepc
  labels:
    app: srsepc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srsepc
  template:
    metadata:
      labels:
        app: srsepc
    spec:
      containers:
      - name: srsepc
        image: srsran:latest
        imagePullPolicy: Never
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - SYS_NICE
        volumeMounts:
        - name: tun
          mountPath: /dev/net/tun
      volumes:
      - name: tun
        hostPath:
          path: /dev/net/tun
          type: CharDevice
      restartPolicy: Always
