---
apiVersion: v1
kind: ConfigMap
metadata:
  name: srsepc-config
  namespace: srsran
data:
  epc.conf: |
    [mme]
    mme_code = 0x1a
    mme_group = 0x0001
    tac = 0x0007
    mcc = 001
    mnc = 01
    mme_bind_addr = 0.0.0.0
    apn = srsapn
    dns_addr = 8.8.8.8
    encryption_algo = EEA0
    integrity_algo = EIA1
    paging_timer = 2

    [hss]
    db_file = user_db.csv

    [spgw]
    gtpu_bind_addr = 0.0.0.0
    sgi_if_addr = 172.16.0.1
    sgi_if_name = sgi_if
    max_paging_queue = 100

    [pcrf]
    
  user_db.csv: |
    #                                                                                           
    # .csv to store UE's information in HSS                                                    
    # Kept in the following format: "Name,IMSI,Key,OP_Type,OP,AMF,QCI,IP_alloc"               
    #                                                                                           
    # Name:     Human readable name to help distinguish UE's. Ignored by the HSS               
    # IMSI:     UE's IMSI value                                                                
    # Key:      UE's key, where other keys are derived from. Stored in hexadecimal             
    # OP_Type:  Operator's code type, either OP or OPc                                         
    # OP/OPc:   Operator Code/Cyphered Operator Code, stored in hexadecimal                    
    # AMF:      Authentication management field, stored in hexadecimal                         
    # QCI:      QoS Class Identifier for the UE's default bearer.                              
    # IP_alloc: IP allocation stratagy for the SPGW.                                           
    #           With 'dynamic' the SPGW will automatically allocate IPs                        
    #           With a valid IPv4 (e.g. '172.16.0.2') the UE will have a statically assigned IP.
    #
    # Note: Lines starting by '#' are ignored and will be overwritten
    ue1,001010123456780,00112233445566778899aabbccddeeff,opc,63bfa50ee6523365ff14c1f45f88737d,8000,9,dynamic
