---
apiVersion: v1
kind: ConfigMap
metadata:
  name: srsue-config
  namespace: srsran
data:
  ue.conf: |
    [rat.eutra]
    dl_earfcn = 3400
    nof_carriers = 1
    
    [rat.nr]
    bands = 78
    nof_carriers = 0
    
    [pcap]
    enable = none
    mac_filename = /tmp/ue_mac.pcap
    mac_nr_filename = /tmp/ue_mac_nr.pcap
    nas_filename = /tmp/ue_nas.pcap
    
    [log]
    all_level = info
    phy_lib_level = warning
    all_hex_limit = 32
    filename = /tmp/ue.log
    file_max_size = -1
    
    [usim]
    mode = soft
    algo = milenage
    opc  = 63bfa50ee6523365ff14c1f45f88737d
    k    = 00112233445566778899aabbccddeeff
    imsi = 001010123456780
    imei = 353490069873319
    
    [rrc]
    release = 15
    ue_category = 4
    
    [nas]
    apn = srsapn
    apn_protocol = ipv4
    
    [gw]
    netns = ue1
    ip_devname = tun_srsue
    ip_netmask = 255.255.255.0
    
    [gui]
    enable = false
    
    [rf]
    device_name = zmq
    device_args = tx_port=tcp://*:2001,rx_port=tcp://srsenb.srsran.svc.cluster.local:2000,id=ue,base_srate=23.04e6
    tx_gain = 80
    rx_gain = 40
    freq_offset = 0
